# Generated by Django 3.1.7 on 2021-03-20 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20210319_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncard',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
            preserve_default=False,
        ),
    ]
