# Generated by Django 3.1.7 on 2021-03-20 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_collectioncard_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncard',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_cards', to='collection.collection'),
        ),
    ]
