# Generated by Django 3.1.7 on 2021-03-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_auto_20210320_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioncard',
            name='set_has_foil',
        ),
    ]
