# Generated by Django 3.1.7 on 2021-03-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0002_set_parent_set'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='set',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, name=''), name='non_empty_name'),
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, name=''), name='non_empty_code'),
        ),
    ]
