# Generated by Django 3.1.7 on 2021-03-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0004_auto_20210319_0124'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='set',
            name='non_empty_name',
        ),
        migrations.RemoveConstraint(
            model_name='set',
            name='non_empty_code',
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.CheckConstraint(check=models.Q(name__length__gt=0), name='non_empty_name'),
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.CheckConstraint(check=models.Q(code__length__gt=0), name='non_empty_code'),
        ),
    ]
