# Generated by Django 3.1.7 on 2021-03-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0005_auto_20210319_0135'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='set',
            name='non_empty_name',
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(check=models.Q(name__length__gt=0), name='non_empty_card_name'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(check=models.Q(ascii_name__length__gt=0), name='non_empty_ascii_name'),
        ),
        migrations.AddConstraint(
            model_name='printing',
            constraint=models.CheckConstraint(check=models.Q(border__length__gt=0), name='non_empty_border'),
        ),
        migrations.AddConstraint(
            model_name='printing',
            constraint=models.CheckConstraint(check=models.Q(border_color__length__gt=0), name='non_empty_border_color'),
        ),
        migrations.AddConstraint(
            model_name='printing',
            constraint=models.CheckConstraint(check=models.Q(border_effect__length__gt=0), name='non_empty_border_effect'),
        ),
        migrations.AddConstraint(
            model_name='printing',
            constraint=models.CheckConstraint(check=models.Q(layout__length__gt=0), name='non_empty_layout'),
        ),
        migrations.AddConstraint(
            model_name='printing',
            constraint=models.CheckConstraint(check=models.Q(number__length__gt=0), name='non_empty_number'),
        ),
        migrations.AddConstraint(
            model_name='printing',
            constraint=models.CheckConstraint(check=models.Q(rarity__length__gt=0), name='non_empty_rarity'),
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.CheckConstraint(check=models.Q(name__length__gt=0), name='non_empty_set_name'),
        ),
    ]
