# Generated by Django 3.1.7 on 2021-03-19 03:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0006_auto_20210319_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color_identity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green'), ('C', 'Colorless')], max_length=6), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green'), ('C', 'Colorless')], max_length=6), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtypes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='supertypes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='printing',
            name='associated_cards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='printing',
            name='promo_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], size=None),
        ),
    ]
