# Generated by Django 3.1.7 on 2021-03-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0008_auto_20210319_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
