# Generated by Django 3.1.7 on 2021-03-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0009_auto_20210319_0327'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(check=models.Q(name__length__gt=0), name='non_empty_artist_name'),
        ),
    ]
