# Generated by Django 3.1.7 on 2021-03-19 03:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0010_auto_20210319_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printing',
            name='border_effect',
        ),
        migrations.AddField(
            model_name='printing',
            name='border_effects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
    ]
