# Generated by Django 3.1.7 on 2021-03-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0011_auto_20210319_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='reserved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='printing',
            name='full_art',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
