# Generated by Django 3.1.7 on 2021-03-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0013_auto_20210319_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='flavor_text',
            field=models.TextField(blank=True),
        ),
    ]
