# Generated by Django 3.1.7 on 2021-03-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0014_auto_20210319_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printing',
            name='side',
        ),
        migrations.AddField(
            model_name='card',
            name='side',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
