# Generated by Django 3.1.7 on 2021-03-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0016_auto_20210319_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='manacost',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
