# Generated by Django 3.1.7 on 2021-03-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0017_auto_20210319_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='printings',
        ),
        migrations.RemoveField(
            model_name='card',
            name='sets',
        ),
        migrations.AddField(
            model_name='printing',
            name='card',
            field=models.ForeignKey(default=68492, on_delete=django.db.models.deletion.CASCADE, related_name='printings', to='mtg.card'),
            preserve_default=False,
        ),
    ]
