# Generated by Django 3.1.7 on 2021-03-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0018_auto_20210319_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='printing',
            name='is_alternative',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
