# Generated by Django 3.1.7 on 2021-03-19 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0019_printing_is_alternative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printing',
            name='languages',
        ),
        migrations.AddField(
            model_name='set',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=[], size=None),
            preserve_default=False,
        ),
    ]
