# Generated by Django 3.1.7 on 2021-03-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0020_auto_20210319_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printings', to='mtg.artist'),
        ),
        migrations.AlterField(
            model_name='printing',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printings', to='mtg.set'),
        ),
    ]
